# Generated by Django 3.0.6 on 2020-09-21 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TF_app', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
