# Generated by Django 3.0.6 on 2020-09-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TF_app', '0003_register_create_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
