# Generated by Django 3.0.6 on 2020-09-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TF_app', '0004_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
