# Generated by Django 3.0.6 on 2020-09-28 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TF_app', '0005_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_url', models.URLField()),
                ('create_on', models.DateField(default=django.utils.timezone.now)),
                ('update_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('upload_image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
